app = "lunalimpia"
primary_region = "bog"

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "lunalimpia.settings"
  PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[mounts]
  source = "datos"
  destination = "/data"

[vm]
  memory = 256
  cpu_kind = "shared"
  cpus = 1  # Usas 1 CPU compartido
