# Generated by Django 5.2.3 on 2025-06-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='nombre',
        ),
    ]
