# Generated by Django 5.2.1 on 2025-07-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_profesional_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='video',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TextField(),
        ),
    ]
