# Generated by Django 5.2.1 on 2025-07-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_cedula_alter_cliente_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
