# Generated by Django 5.2.1 on 2025-07-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_turno_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='cedula',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
